In [4]:
from preprocessing.video import Video
from preprocessing.dto.sequence_dto import SequenceDto
from preprocessing.inference_service.external_model.yolov7_pose_tracker.utils.plots import plot_one_box_kpt, \
    plot_skeleton_kpts
from pathlib import Path
import cv2
import numpy as np

v = Video(Path('/home/rafa/SVW/Videos/tennis/145___14d52737e37b4fbe8b4aadf4fecaa78a.mp4'))
detections = v.build_detections()
detections.head()

video  frame_id  \
0  /home/rafa/SVW/Videos/tennis/145___14d52737e37...         2   
1  /home/rafa/SVW/Videos/tennis/145___14d52737e37...         3   
2  /home/rafa/SVW/Videos/tennis/145___14d52737e37...         4   
3  /home/rafa/SVW/Videos/tennis/145___14d52737e37...         5   
4  /home/rafa/SVW/Videos/tennis/145___14d52737e37...         6   

                   bbox                                           skeleton  \
0  [632, 544, 406, 312]  [946.91504, 592.6226, 0.14632297, 945.3374, 58...   
1  [660, 545, 387, 312]  [953.19403, 592.3683, 0.11643667, 952.63556, 5...   
2  [667, 549, 378, 307]  [960.3724, 591.94763, 0.084336884, 958.172, 58...   
3  [680, 545, 352, 312]  [968.39777, 593.86774, 0.12125801, 967.0138, 5...   
4  [685, 543, 358, 313]  [974.13806, 593.6012, 0.11915024, 972.41223, 5...   

        score  person_id         unique_color  \
0  0.87011963          1  [82.0, 84.0, 163.0]   
1  0.91835827          1  [82.0, 84.0, 163.0]   
2  0.86277264          1  [82.0, 84.0, 163.0]   
3   0.8897601          1  [82.0, 84.0, 163.0]   
4  0.90482575          1  [82.0, 84.0, 163.0]   

                                     visual_features  
0  [3.9034505, 0.009452351, 1.1675202, 0.7402939,...  
1  [1.4132752, 4.209793, 0.55654645, -0.0, 25.870...  
2  [0.9617565, 6.1015034, 0.2915246, -0.0, 26.472...  
3  [2.8970196, -0.0, 2.2446182, -0.0, 24.212563, ...  
4  [3.649752, 0.35856, 1.5218177, -0.0, 25.153744...

In [5]:
cap = cv2.VideoCapture(v.video_reshaped_path.as_posix())
video = [np.zeros((1080, 1920, 3))]
while (cap.isOpened()):
    ret, img = cap.read()
    if not ret:
        break
    video.append(img)
cap.release()



In [6]:

from preprocessing.dto.detection_dto import DetectionDto

persons = detections[DetectionDto.PERSON_ID].unique()
frames = detections[DetectionDto.FRAME_ID].unique()
for frame in frames:
    # frame = np.zeros
    skeletons = detections[detections[DetectionDto.FRAME_ID] ==frame]["skeleton"]
    bboxes = detections[detections[DetectionDto.FRAME_ID] ==frame]["bbox"]
    colors = detections[detections[DetectionDto.FRAME_ID] ==frame]["unique_color"]
    frame_img = video[frame]
    for bbox, skeleton, color in zip(bboxes, skeletons, colors):
        accs = np.average(skeleton[2::3])
        if accs < 0.5:
            continue
        x = [bbox[0], bbox[1], bbox[0] + bbox[2], bbox[1] + bbox[3]]
        plot_one_box_kpt(x=x, im=frame_img, kpt_label=True, kpts=skeleton, steps=3, color=color, line_thickness=10)
        print(skeleton.reshape((-1, 3)))
    cv2.imshow('frame', frame_img)
    cv2.waitKey(0)
cv2.destroyAllWindows()

[[     946.92      592.62     0.14632]
 [     945.34      585.03   0.0092133]
 [     946.18      583.74     0.18538]
 [     889.18      576.14      0.1604]
 [     929.77      581.59     0.76687]
 [     824.65       596.7     0.95336]
 [     937.42      610.96     0.96242]
 [     749.79      603.02     0.90177]
 [     1009.5      636.94      0.9262]
 [      681.5      634.36     0.83531]
 [     1016.9      666.44     0.86394]
 [     796.66      678.62     0.97298]
 [     871.95      683.68     0.97476]
 [     794.86      720.52     0.96635]
 [     919.19      730.83     0.97002]
 [     798.15      793.53     0.92922]
 [     908.13      821.48     0.93343]]


QObject::moveToThread: Current thread (0xa354120) is not the object's thread (0x9b017a0).
Cannot move to target thread (0xa354120)

QObject::moveToThread: Current thread (0xa354120) is not the object's thread (0x9b017a0).
Cannot move to target thread (0xa354120)

QObject::moveToThread: Current thread (0xa354120) is not the object's thread (0x9b017a0).
Cannot move to target thread (0xa354120)

QObject::moveToThread: Current thread (0xa354120) is not the object's thread (0x9b017a0).
Cannot move to target thread (0xa354120)

QObject::moveToThread: Current thread (0xa354120) is not the object's thread (0x9b017a0).
Cannot move to target thread (0xa354120)

QObject::moveToThread: Current thread (0xa354120) is not the object's thread (0x9b017a0).
Cannot move to target thread (0xa354120)

QObject::moveToThread: Current thread (0xa354120) is not the object's thread (0x9b017a0).
Cannot move to target thread (0xa354120)

QObject::moveToThread: Current thread (0xa354120) is not the object's thread

[[     953.19      592.37     0.11644]
 [     952.64      584.61   0.0078863]
 [     953.29      583.27     0.14132]
 [     895.03      574.83     0.17379]
 [     934.23      581.18     0.76618]
 [     822.77      597.18     0.95377]
 [     938.59      612.66     0.96202]
 [     744.48      608.52     0.90392]
 [     1007.2      631.21     0.92641]
 [      691.7       635.7     0.83604]
 [     1021.1      652.33     0.86325]
 [     804.53      681.98     0.97482]
 [     881.24      687.32     0.97634]
 [     803.89      730.51      0.9667]
 [     921.54      744.31     0.97003]
 [     804.72       794.6     0.92656]
 [     914.85      823.39     0.93013]]
[[     960.37      591.95    0.084337]
 [     958.17      585.49   0.0073304]
 [      959.4      584.59    0.089293]
 [     900.15      574.53     0.19212]
 [     940.03      585.11     0.72026]
 [     825.55      600.39     0.94122]
 [     944.69      616.65      0.9468]
 [     739.74      620.22     0.88771]
 [     992.12      640.3